name: Front-End CI/CD 

on: 
  push: 
  pull_request:

env:
  DIR: ${{ github.workspace }}/orelease-etc-frontend/er-to-code/

jobs:
  # Building pipeline
  frontend: 
    name: Build and Test
    runs-on: ubuntu-latest
 
    steps: 
      # chechout the repo: 
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Install Node
        uses: actions/setup-node@v3
        with: 
          node-versions: 18
          
      - name: Install dependencies
        run: npm install
        working-directory: ${{ env.DIR }}

      - name: Add Missing Babel Dependency
        run: npm install --save-dev @babel/plugin-proposal-private-property-in-object
        working-directory: ${{ env.FRONTEND_PATH }}

      - name: run tests
        run: npm test
        working-directory: ${{ env.DIR }}


  cleanup:
    name: Clean files
    runs-on: ubuntu-latest
    needs: frontend
    
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Debug Directory
        run: |
          echo "Current working directory: $(pwd)"
          echo "Checking directory contents:"
          ls -al ${{ env.DIR }}

      - name: Ensure Directory Exists
        run: mkdir -p ${{ env.DIR }}

      - name: Clean Cache
        run: npm cache clean --force 

      - name: Remove Modules
        run: rm -rf node_modules
        working-directory: ${{ env.DIR }}

      - name: Remove Build Directory
        run: rm -rf build
        working-directory: ${{ env.DIR }}

      - name: Confirm Clean
        run: |
          if [ -d node_modules ] || [ -d build ]; then
            echo "Cleanup failed: Directories still exist"
            exit 1
          else
            echo "Cleanup successful: Directories removed"
          fi
        working-directory: ${{ env.DIR }}
